version: "3.7"

services:
  #########################################################
  # backend's env
  #########################################################
  backend_app_server:
    container_name: ${BACKEND_APP_CONTAINER_NAME}
    build:
      context: ./backend/backend_app_server/.
      dockerfile: Dockerfile.development
      target: development
    volumes:
      - ./backend/backend_app_server/app:/root/src
    ports:
      - "${BACKEND_APP_SOURCE_PORT}:${BACKEND_APP_DESTINATION_PORT}"
    environment:
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DESTINATION_PORT: ${DB_DESTINATION_PORT}
      DB_HOST: ${DB_HOST}
      DB_CONTAINER_NAME: ${DB_CONTAINER_NAME}
      SECRET_KEY: ${SECRET_KEY}
    stdin_open: true
    tty: true
    depends_on:
      - db

  #########################################################
  # database env
  #########################################################
  db:
    container_name: ${DB_CONTAINER_NAME}
    build:
      context: ./db/env/.
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "${DB_SOURCE_PORT}:${DB_DESTINATION_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${DB_TZ}
    volumes:
      - ./db/db_volume:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d

  #########################################################
  # frontend's env
  #########################################################
  frontend_app_server:
    build:
      context: ./frontend/frontend_app_server/.
      dockerfile: Dockerfile.development
    container_name: ${FRONTEND_APP_CONTAINER_NAME}
    volumes:
      - ./frontend/frontend_app_server/app:/root/src
    tty: true
    ports:
      - "${FRONTEND_APP_SOURCE_PORT}:${FRONTEND_APP_DESTINATION_PORT}"